import { build } from "esbuild";
import fs from "fs";
import path from "path";
import os from "os";

// freeze-dry depends on postcss-values-parser which uses util.format;
// esbuild doesn't polyfill Node built-ins for browser bundles, so we
// inject a minimal shim
const utilShimPath = path.join(os.tmpdir(), "util-shim.js");
fs.writeFileSync(
  utilShimPath,
  `export function format(fmt, ...args) {
    let i = 0;
    return String(fmt).replace(/%[sdj%]/g, (m) => {
      if (m === "%%") return "%";
      return i < args.length ? String(args[i++]) : m;
    });
  }
  export default { format };`,
);

await build({
  entryPoints: [
    path.resolve(
      import.meta.dirname,
      "../node_modules/freeze-dry/lib/index.js",
    ),
  ],
  bundle: true,
  format: "iife",
  platform: "browser",
  globalName: "__freezeDryModule",
  alias: { util: utilShimPath },
  define: {
    "process.env.NODE_ENV": '"production"',
    process: '{"env":{}}',
  },
  outfile: path.resolve(
    import.meta.dirname,
    "../src/sources/pinboard/assets/freeze-dry-browserified.js",
  ),
  footer: {
    js: "window.freezeDry = () => __freezeDryModule.default();",
  },
});

console.log("freeze-dry bundled");

// The built output is bundled and chunked by tsup, so a path resolved from
// import.meta.dirname at runtime does not reliably point anywhere the asset
// was copied to. Emitting the bundle as a module instead puts it inside the
// bundle, where it cannot go missing.
const bundlePath = path.resolve(
  import.meta.dirname,
  "../src/sources/pinboard/assets/freeze-dry-browserified.js",
);
fs.writeFileSync(
  path.resolve(
    import.meta.dirname,
    "../src/sources/pinboard/assets/freeze-dry-source.ts",
  ),
  `// generated by scripts/compile-freeze-dry.ts - do not edit\nexport const FREEZE_DRY_SRC = ${JSON.stringify(
    fs.readFileSync(bundlePath, "utf-8"),
  )};\n`,
  "utf-8",
);

console.log("freeze-dry source module emitted");
